// Generated by IcedCoffeeScript 1.6.2c
(function() {


  exports.zoomCanvas = require('./lib/zoom-canvas').zoomCanvas;

  exports.ezCanvas = require('./lib/ez-canvas').ezCanvas;

  exports.ezStack = require('./lib/ez-stack').ezStack;

  exports.colorWizard = require('./lib/color-wizard').colorWizard;

}).call(this);
