// Generated by IcedCoffeeScript 1.6.2c
(function() {


  exports.zoomCanvas = require('./zoom-canvas').zoomCanvas;

  exports.ezCanvas = require('./ez-canvas').ezCanvas;

  exports.colorWizard = require('./color-wizard').colorWizard;

}).call(this);
