// Generated by IcedCoffeeScript 1.6.2c
(function() {
  var cw, k, v;



  cw = {
    darken: function(c, frac) {
      var res;
      res = [c[0] * (1 - frac), c[1] * (1 - frac), c[2] * (1 - frac)];
      if (c[3] != null) {
        res[3] = c[3] * (1 - frac);
      }
      return res;
    },
    lighten: function(c, frac) {
      var res;
      res = [c[0] + (255 - c[0]) * frac, c[1] + (255 - c[1]) * frac, c[2] + (255 - c[2]) * frac];
      if (c[3] != null) {
        res[3] = c[3] + (255 - c[3]) * frac;
      }
      return res;
    },
    hex255: function(n) {
      return Math.floor(n / 16).toString(16) + (n % 16).toString(16);
    },
    hex: function(c) {
      var res;
      res = "" + (cw.hex255(~~c[0])) + (cw.hex255(~~c[1])) + (cw.hex255(~~c[2]));
      if (c[3] != null) {
        res += cw.hex255(~~c[3]);
      }
      return res;
    }
  };

  for (k in cw) {
    v = cw[k];
    exports[k] = v;
  }

}).call(this);
