// Generated by CoffeeScript 1.3.3
(function() {
  var rect;

  rect = (function() {

    function rect(_arg) {
      var ll, ur;
      ll = _arg.ll, ur = _arg.ur;
      this.ll = ll || null;
      this.ur = ur || null;
    }

    rect.prototype.copy = function() {
      var r;
      return r = new boundingRect({
        ll: this.ll.copy(),
        lr: this.lr.copy()
      });
    };

    return rect;

  })();

  exports.rect = rect;

}).call(this);
