// Generated by IcedCoffeeScript 1.6.2c
(function() {
  var vec;



  vec = (function() {
    function vec(x, y) {
      this.x = x;
      this.y = y;
    }

    vec.prototype.zero = function() {
      return this.x = this.y = 0;
    };

    vec.prototype.copy = function() {
      return new vec(this.x, this.y);
    };

    return vec;

  })();

  exports.vec = vec;

}).call(this);
