// Generated by CoffeeScript 1.3.3
(function() {
  var rect, vec, zoomCanvas;

  vec = require('./vec').vec;

  rect = require('./rect').rect;

  zoomCanvas = (function() {

    function zoomCanvas(options) {
      /*
            options:
              canvas_width:  width of the canvas targeted
              canvas_height: height of the canvas targeted
              fill:          fraction of canvas to keep filled; 0.8 means 20% margins
              spring_k:      spring constant for zoom snapping
              spring_damp:   spring dampeining for zoom snapping
      */
      options |= {};
      this.cw = options.canvas_width || null;
      this.ch = options.canvas_height || null;
      this.fill = options.fill || 1.0;
      this.spring_k = options.spring_k != null ? options.spring_k : 1.0;
      this.spring_damp = options.spring_damp != null ? options.spring_damp : 1.0;
      this.drawScale = null;
      this.bounds = {
        target: new this.rect(),
        actual: new this.rect(),
        vel: {
          ll: new this.vec(0, 0),
          ur: new this.vec(0, 0)
        }
      };
    }

    zoomCanvas.prototype.setObjectBounds = function() {};

    zoomCanvas.prototype.calcObjectBounds = function() {};

    zoomCanvas.prototype.instantZoom = function() {
      this.bounds.vel.ll.zero();
      this.bounds.vel.ur.zero();
      return this.bounds.actual = this.bounds.target.copy();
    };

    return zoomCanvas;

  })();

  exports.zoomCanvas = zoomCanvas;

}).call(this);
